import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import * as csv from 'csv-stringify/sync';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import PDFDocument from 'pdfkit';
import pdfParse from 'pdf-parse';

// ===================== FILE CREATION =====================

export interface CreateOptions {
  title?: string;
  headers?: string;
  rows?: string;
  data?: string;
  outputDir?: string;
  styled?: boolean;
  paragraphs?: string;
}

export async function createFile(
  fileType: string,
  filename: string,
  content: string = '',
  options: CreateOptions = {}
): Promise<string> {
  let outputPath: string;

  if (options.outputDir) {
    outputPath = path.join(options.outputDir, filename);
  } else {
    outputPath = path.join(os.homedir(), filename);
  }

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  try {
    switch (fileType.toLowerCase()) {
      case 'txt':
        return createTxt(outputPath, content);

      case 'md':
        return createMarkdown(outputPath, content, options);

      case 'json':
        return createJson(outputPath, content);

      case 'csv':
        return createCsv(outputPath, options);

      case 'html':
        return createHtml(outputPath, content, options);

      case 'docx':
        return await createDocx(outputPath, content, options);

      case 'pdf':
        return await createPdf(outputPath, content, options);

      default:
        return `Unknown file type: ${fileType}. Supported: txt, md, json, csv, html, docx, pdf`;
    }
  } catch (e) {
    return `Error creating file: ${e instanceof Error ? e.message : String(e)}`;
  }
}

function createTxt(outputPath: string, content: string): string {
  fs.writeFileSync(outputPath, content, 'utf8');
  return `Created TXT file: ${outputPath} (${content.length} characters)`;
}

function createMarkdown(outputPath: string, content: string, options: CreateOptions): string {
  const title = options.title || 'Document';
  const lines = [`# ${title}`, ''];

  if (content) {
    lines.push(content);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by Universal Toolkit*');

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
  return `Created Markdown file: ${outputPath}`;
}

function createJson(outputPath: string, content: string): string {
  let data: any;

  if (content) {
    try {
      data = JSON.parse(content);
    } catch (e) {
      return `Error: Invalid JSON content.`;
    }
  } else {
    data = {};
  }

  const jsonStr = JSON.stringify(data, null, 2);
  fs.writeFileSync(outputPath, jsonStr, 'utf8');
  return `Created JSON file: ${outputPath} (${jsonStr.length} bytes)`;
}

function parseCsvRow(row: string): string[] {
  const cells: string[] = [];
  let current = '';
  let inQuotes = false;
  for (let i = 0; i < row.length; i++) {
    const char = row[i];
    if (char === '"') {
      inQuotes = !inQuotes;
    } else if (char === ',' && !inQuotes) {
      cells.push(current.trim());
      current = '';
    } else {
      current += char;
    }
  }
  cells.push(current.trim());
  return cells;
}

// BUG-42 FIX: Proper CSV parser that handles quoted fields with embedded newlines
function parseCsvContent(content: string): string[][] {
  const rows: string[][] = [];
  let currentRow: string[] = [];
  let currentField = '';
  let inQuotes = false;
  let i = 0;
  
  while (i < content.length) {
    const char = content[i];
    
    if (inQuotes) {
      if (char === '"') {
        // Check for escaped quote (double quote)
        if (i + 1 < content.length && content[i + 1] === '"') {
          currentField += '"';
          i += 2;
        } else {
          // End of quoted field
          inQuotes = false;
          i++;
        }
      } else {
        currentField += char;
        i++;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
        i++;
      } else if (char === ',') {
        currentRow.push(currentField);
        currentField = '';
        i++;
      } else if (char === '\n' || char === '\r') {
        // Handle \r\n and \n line endings
        if (char === '\r' && i + 1 < content.length && content[i + 1] === '\n') {
          i++;
        }
        currentRow.push(currentField);
        if (currentRow.length > 0 || currentField !== '') {
          rows.push(currentRow);
        }
        currentRow = [];
        currentField = '';
        i++;
      } else {
        currentField += char;
        i++;
      }
    }
  }
  
  // Add the last field/row
  if (currentField !== '' || currentRow.length > 0) {
    currentRow.push(currentField);
    rows.push(currentRow);
  }
  
  // Filter out empty rows
  return rows.filter(row => row.length > 0 && (row.length > 1 || row[0].trim() !== ''));
}

function createCsv(outputPath: string, options: CreateOptions): string {
  // BUG-51 FIX: Documented default values - headers default to ['Column1', 'Column2'], rows default to [['val1', 'val2']]
  const headers = options.headers ? options.headers.split(',').map(h => h.trim()) : ['Column1', 'Column2'];
  const rows = options.rows
    ? options.rows.split('|').map(r => parseCsvRow(r))
    : [['val1', 'val2']]; // Default: one row with two columns

  // BUG-10 FIX: csv-stringify handles quoting automatically for values with commas
  // Updated for csv-stringify v6: columns option removed (not needed for array-of-arrays)
  const stringified = csv.stringify([headers, ...rows], {
    header: false,
    delimiter: ',',
    record_delimiter: '\n'
  });

  fs.writeFileSync(outputPath, stringified, 'utf8');
  return `Created CSV file: ${outputPath} (${rows.length} rows, ${headers.length} columns)`;
}

function createHtml(outputPath: string, content: string, options: CreateOptions): string {
  const title = options.title || 'Document';
  const styled = options.styled !== false;

  if (styled) {
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
            max-width: 900px;
            margin: 40px auto;
            padding: 0 20px;
            line-height: 1.6;
            color: #333;
            background-color: #fafafa;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 3px solid #3498db;
            padding-bottom: 10px;
        }
        h2 { color: #34495e; }
        p { margin: 1em 0; }
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        pre {
            background: #2d2d2d;
            color: #f8f8f2;
            padding: 16px;
            border-radius: 6px;
            overflow-x: auto;
        }
        a { color: #3498db; }
        footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #888;
            font-size: 0.9em;
        }
    </style>
</head>
<body>
    <h1>${title}</h1>
    ${content || '<p>This document was created by the Universal Toolkit.</p>'}
    <footer>
        <p>Generated by Universal Toolkit</p>
    </footer>
</body>
</html>`;
    fs.writeFileSync(outputPath, html, 'utf8');
  } else {
    const html = `<!DOCTYPE html>
<html>
<head><title>${title}</title></head>
<body>
    <h1>${title}</h1>
    ${content || '<p>This document was created by the Universal Toolkit.</p>'}
</body>
</html>`;
    fs.writeFileSync(outputPath, html, 'utf8');
  }

  return `Created HTML file: ${outputPath}`;
}

async function createDocx(outputPath: string, content: string, options: CreateOptions): Promise<string> {
  const title = options.title || 'Document';
  const paragraphs: string[] = options.paragraphs
    ? options.paragraphs.split('|').map(p => p.trim())
    : content ? content.split('\n') : [];

  const docChildren: Paragraph[] = [
    new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 48 })],
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 }
    })
  ];

  if (paragraphs.length > 0) {
    paragraphs.forEach(para => {
      if (para.trim()) {
        docChildren.push(
          new Paragraph({
            children: [new TextRun(para)],
            spacing: { after: 200 }
          })
        );
      }
    });
  }

  if (content && !options.paragraphs) {
    content.split('\n').forEach(line => {
      if (line.trim()) {
        docChildren.push(
          new Paragraph({
            children: [new TextRun(line)],
            spacing: { after: 200 }
          })
        );
      }
    });
  }

  const doc = new Document({
    sections: [{
      properties: {},
      children: docChildren,
    }],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outputPath, buffer);
  return `Created DOCX file: ${outputPath} (${buffer.length} bytes)`;
}

async function createPdf(outputPath: string, content: string, options: CreateOptions): Promise<string> {
  const doc = new PDFDocument({ autoFirstPage: false });
  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  // BUG-30 FIX: Add a page before writing content (autoFirstPage: false means no page is created automatically)
  doc.addPage();

  const title = options.title || 'Document';

  // Title
  doc.fontSize(28).text(title, {
    align: 'center',
    underline: true
  });

  doc.moveDown(1);

  // Content
  if (content) {
    const lines = content.split('\n');
    // BUG-57 FIX: Add max-lines limit to prevent memory issues with large content
    const maxLines = 10000;
    const limitedLines = lines.slice(0, maxLines);
    limitedLines.forEach(line => {
      doc.fontSize(12).text(line, {
        align: 'left',
        indent: 20
      });
      doc.moveDown(0.3);
    });
    if (lines.length > maxLines) {
      doc.fontSize(10).fillColor('#999').text(`... [truncated, ${lines.length - maxLines} lines omitted]`, {
        align: 'left',
        indent: 20
      }).fillColor('#000000');
    }
  } else {
    doc.fontSize(12).text('This document was created by the Universal Toolkit.', {
      align: 'left',
      indent: 20
    });
  }

  doc.end();

  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', (err) => reject(err));
  });

  return `Created PDF file: ${outputPath}`;
}

// ===================== FILE READING =====================

export async function readFile(filepath: string): Promise<string> {
  const filePath = path.resolve(filepath);

  if (!fs.existsSync(filePath)) {
    return `Error: File not found: ${filepath}`;
  }

  const ext = path.extname(filePath).toLowerCase();
  const stat = fs.statSync(filePath);

  try {
    switch (ext) {
      case '.txt':
        return readTxt(filePath, stat);

      case '.md':
        return readMarkdown(filePath, stat);

      case '.json':
        return readJson(filePath, stat);

      case '.csv':
        return readCsv(filePath, stat);

      case '.html':
      case '.htm':
        return await readHtml(filePath, stat);

      case '.docx':
        return readDocx(filePath, stat);

      case '.pdf':
        return readPdf(filePath, stat);

      default:
        return `Unsupported file type: ${ext}. Supported: .txt, .md, .json, .csv, .html, .docx, .pdf`;
    }
  } catch (e) {
    return `Error reading file: ${e instanceof Error ? e.message : String(e)}`;
  }
}

function readTxt(filePath: string, stat: fs.Stats): string {
  const content = fs.readFileSync(filePath, 'utf8');
  return `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n${content}`;
}

function readMarkdown(filePath: string, stat: fs.Stats): string {
  const content = fs.readFileSync(filePath, 'utf8');
  return `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n${content}`;
}

function readJson(filePath: string, stat: fs.Stats): string {
  const content = fs.readFileSync(filePath, 'utf8');
  let data: any;
  try {
    data = JSON.parse(content);
  } catch (e) {
    return `Error: Invalid JSON in ${filePath}: ${e instanceof Error ? e.message : String(e)}`;
  }
  return `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n${JSON.stringify(data, null, 2)}`;
}

function readCsv(filePath: string, stat: fs.Stats): string {
  const content = fs.readFileSync(filePath, 'utf8');
  // BUG-42 FIX: Handle newlines in quoted fields by parsing CSV properly
  // The csv-stringify library has a corresponding parse function we can use
  let rows: string[][];
  try {
    // Use csv-stringify's parse (it exports parse as well)
    // For now, implement a simple state-machine parser for quoted fields
    rows = parseCsvContent(content);
  } catch (e) {
    // Fallback to simple split if parsing fails
    rows = content.split('\n').map(row => parseCsvRow(row)).filter(row => row.length > 0 && (row.length > 1 || row[0].trim() !== ''));
  }

  if (rows.length === 0) {
    return `--- ${filePath} (empty file) ---`;
  }

  const maxRows = Math.min(rows.length, 51);
  const header = rows[0];
  const colWidths = header.map((_: string, colIdx: number) =>
    Math.max(
      header[colIdx].length,
      ...rows.slice(1, Math.min(rows.length, 51)).map(row => row[colIdx]?.length || 0)
    )
  );

  let output = `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n`;
  output += `Rows: ${rows.length - 1} | Columns: ${header.length}\n`;
  output += '='.repeat(70) + '\n\n';

  // Header
  const headerStr = header.map((h: string, i: number) => h.padEnd(Math.min(colWidths[i], 30))).join(' | ');
  output += headerStr + '\n';
  output += '-'.repeat(headerStr.length) + '\n';

  // Data rows
  for (let i = 1; i < maxRows; i++) {
    const row = rows[i];
    const rowStr = header.map((_: string, j: number) => (row[j] || '').padEnd(Math.min(colWidths[j], 30))).join(' | ');
    output += `${String(i).padStart(4)} | ${rowStr}\n`;
  }

  if (rows.length > maxRows) {
    output += `\n... and ${rows.length - maxRows} more rows\n`;
  }

  return output;
}

async function readHtml(filePath: string, stat: fs.Stats): Promise<string> {
  const html = fs.readFileSync(filePath, 'utf8');

  try {
    const { default: cheerio } = await import('cheerio');
    const $ = cheerio.load(html);
    const title = $('title').text() || 'No title';
    const links = $('a[href]');

    let output = `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n`;
    output += `Title: ${title}\n`;
    output += `Links: ${links.length}\n`;
    output += '='.repeat(70) + '\n\n';

    // Extract paragraphs
    $('p, h1, h2, h3, h4, h5, h6, li').each((_: any, el: any) => {
      const text = $(el).text().trim();
      if (text) {
        output += text + '\n';
      }
    });

    // Show links
    if (links.length > 0) {
      output += '\n' + '='.repeat(70) + '\n';
      output += 'LINKS:\n';
      links.slice(0, 20).each((_: any, el: any) => {
        const linkText = $(el).text().trim().substring(0, 40);
        const href = $(el).attr('href') || '';
        output += `  ${linkText.padEnd(40)} -> ${href}\n`;
      });
      if (links.length > 20) {
        output += `  ... and ${links.length - 20} more\n`;
      }
    }

    return output;
  } catch (e) {
    return `Error reading HTML: ${e instanceof Error ? e.message : String(e)}`;
  }
}

async function readDocx(filePath: string, stat: fs.Stats): Promise<string> {
  try {
    const { default: JSZip } = await import('jszip');

    const buffer = fs.readFileSync(filePath);
    const zip = await JSZip.loadAsync(buffer);
    const documentXml = await zip.file('word/document.xml')?.async('string');

    if (!documentXml) {
      return `Error: Invalid DOCX file`;
    }

    // Simple text extraction from XML
    const textMatches = documentXml.match(/<w:t[^>]*>([^<]*)<\/w:t>/g) || [];
    const texts = textMatches.map((m: string) => {
      const text = m.match(/>([^<]*)<\/w:t>/);
      return text ? text[1] : '';
    });

    let output = `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n`;
    output += `Paragraphs: ${texts.filter((t: string) => t.trim()).length}\n`;
    output += '='.repeat(70) + '\n\n';

    texts.forEach((text: string, i: number) => {
      if (text.trim()) {
        output += `[${i + 1}] ${text.trim()}\n`;
      }
    });

    return output;
  } catch (e) {
    return `Error reading DOCX: ${e instanceof Error ? e.message : String(e)}. Use a dedicated tool for full DOCX support.`;
  }
}

async function readPdf(filePath: string, stat: fs.Stats): Promise<string> {
  try {
    const buffer = fs.readFileSync(filePath);
    const data = await pdfParse(buffer);

    let output = `--- ${filePath} (${stat.size.toLocaleString()} bytes) ---\n`;
    output += `Pages: ${data.numpages}\n`;
    output += '='.repeat(70) + '\n\n';

    if (data.text && data.text.trim()) {
      output += data.text;
    } else {
      output += '[No extractable text]';
    }

    return output;
  } catch (e) {
    return `Error reading PDF: ${e instanceof Error ? e.message : String(e)}`;
  }
}

// ===================== DIRECTORY SEARCH =====================

export interface SearchOptions {
  pattern?: string;
  extensions?: string;
  minSize?: number;
  maxSize?: number;
  afterDate?: string;
  beforeDate?: string;
  contentQuery?: string;
  recursive?: boolean;
  sortBy?: string;
  caseSensitive?: boolean;
  maxResults?: number;
  showDetails?: boolean;
}

// BUG-FIX: Made searchDirectory async to support fs.promises operations
export async function searchDirectory(
  rootDir: string,
  options: SearchOptions = {}
): Promise<string> {
  const root = path.resolve(rootDir);

  if (!fs.existsSync(root)) {
    return `Error: Directory '${rootDir}' does not exist.`;
  }

  if (!fs.statSync(root).isDirectory()) {
    return `Error: '${rootDir}' is not a directory.`;
  }

  const allResults: SearchResult[] = [];

  try {
    // Name pattern search
    if (options.pattern) {
      // BUG-FIX: Await async search functions
      const results = await searchByName(root, options.pattern, options.recursive !== false, options.caseSensitive || false);
      allResults.push(...results);
    }

    // Extension search
    if (options.extensions) {
      const exts = options.extensions.split(',').map(e => e.trim().replace(/^\./, ''));
      // BUG-FIX: Await async search functions
      const results = await searchByExtension(root, exts, options.recursive !== false);
      allResults.push(...results);
    }

    // Size search
    if (options.minSize !== undefined || options.maxSize !== undefined) {
      // BUG-FIX: Await async search functions
      const results = await searchBySize(root, options.minSize, options.maxSize, options.recursive !== false);
      allResults.push(...results);
    }

    // Date search
    if (options.afterDate || options.beforeDate) {
      // BUG-FIX: Await async search functions
      const results = await searchByDate(root, options.afterDate, options.beforeDate, options.recursive !== false);
      allResults.push(...results);
    }

    // Content search
    if (options.contentQuery) {
      // BUG-FIX: Await async search functions
      const results = await searchContent(root, options.contentQuery, options.recursive !== false, options.pattern, options.caseSensitive || false, options.maxResults || 100);
      allResults.push(...results);
    }

    // Deduplicate by path
    const seen = new Set<string>();
    const unique = allResults.filter(r => {
      if (seen.has(r.path)) return false;
      seen.add(r.path);
      return true;
    });

    // Sort
    let sorted = sortResults(unique, options.sortBy || 'name');

    // Limit
    const maxResults = options.maxResults || 200;
    sorted = sorted.slice(0, maxResults);

    // Format
    const output = formatResults(sorted, options.showDetails !== false);
    return output;

  } catch (e) {
    return `Error searching directory: ${e instanceof Error ? e.message : String(e)}`;
  }
}

interface SearchResult {
  path: string;
  name: string;
  isDir: boolean;
  size?: number;
  modified?: string;
  fileType?: string;
}

function formatSize(sizeBytes: number): string {
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  let size = sizeBytes;
  for (let i = 0; i < units.length; i++) {
    if (size < 1024 || i === units.length - 1) {
      return `${size.toFixed(1)} ${units[i]}`;
    }
    size /= 1024;
  }
  return `${size.toFixed(1)} PB`;
}

function formatDate(timestamp: number): string {
  return new Date(timestamp * 1000).toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit'
  });
}

// BUG-FIX: Made async to use fs.promises.readdir
async function searchByName(rootDir: string, pattern: string, recursive: boolean, caseSensitive: boolean): Promise<SearchResult[]> {
  const results: SearchResult[] = [];
  const searchDir = path.resolve(rootDir);

  async function walk(dir: string) {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (fnmatchMatch(entry.name, pattern, caseSensitive)) {
        const stat = await fs.promises.stat(fullPath);
        results.push({
          path: fullPath,
          name: entry.name,
          isDir: entry.isDirectory(),
          size: entry.isFile() ? stat.size : undefined,
          modified: entry.isFile() ? formatDate(stat.mtimeMs / 1000) : undefined,
          fileType: entry.isFile() ? (path.extname(entry.name).slice(1).toUpperCase() || 'FILE') : 'DIR'
        });
      }

      if (entry.isDirectory() && recursive) {
        await walk(fullPath);
      }
    }
  }

  await walk(searchDir);
  return results;
}

function fnmatchMatch(name: string, pattern: string, caseSensitive: boolean): boolean {
  const n = caseSensitive ? name : name.toLowerCase();
  const p = caseSensitive ? pattern : pattern.toLowerCase();

  // Simple glob matching
  const regex = new RegExp('^' + p.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*/g, '.*').replace(/\?/g, '.') + '$');
  return regex.test(n);
}

// BUG-FIX: Made async to use fs.promises.readdir
async function searchByExtension(rootDir: string, extensions: string[], recursive: boolean): Promise<SearchResult[]> {
  const results: SearchResult[] = [];
  const extSet = new Set(extensions.map(e => e.toLowerCase()));
  const searchDir = path.resolve(rootDir);

  async function walk(dir: string) {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const stat = await fs.promises.stat(fullPath);

      if (entry.isDirectory() && recursive) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        const fileExt = path.extname(entry.name).slice(1).toLowerCase();
        if (extSet.has(fileExt)) {
          results.push({
            path: fullPath,
            name: entry.name,
            isDir: false,
            size: stat.size,
            modified: formatDate(stat.mtimeMs / 1000),
            fileType: fileExt.toUpperCase()
          });
        }
      }
    }
  }

  await walk(searchDir);
  return results;
}

// BUG-FIX: Made async to use fs.promises.readdir
async function searchBySize(rootDir: string, minSize?: number, maxSize?: number, recursive: boolean = true): Promise<SearchResult[]> {
  const results: SearchResult[] = [];
  const searchDir = path.resolve(rootDir);

  async function walk(dir: string) {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const stat = await fs.promises.stat(fullPath);

      if (entry.isDirectory() && recursive) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        if ((minSize === undefined || stat.size >= minSize) &&
            (maxSize === undefined || stat.size <= maxSize)) {
          results.push({
            path: fullPath,
            name: entry.name,
            isDir: false,
            size: stat.size,
            modified: formatDate(stat.mtimeMs / 1000),
            fileType: path.extname(entry.name).slice(1).toUpperCase() || 'FILE'
          });
        }
      }
    }
  }

  await walk(searchDir);
  return results;
}

// BUG-FIX: Made async to use fs.promises.readdir
async function searchByDate(rootDir: string, afterDate?: string, beforeDate?: string, recursive: boolean = true): Promise<SearchResult[]> {
  const results: SearchResult[] = [];
  const searchDir = path.resolve(rootDir);

  const afterMs = afterDate ? new Date(afterDate).getTime() : undefined;
  const beforeMs = beforeDate ? new Date(beforeDate).getTime() : undefined;

  async function walk(dir: string) {
    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const stat = await fs.promises.stat(fullPath);

      if (entry.isDirectory() && recursive) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        const fileMs = stat.mtimeMs;
        if ((afterMs === undefined || fileMs >= afterMs) &&
            (beforeMs === undefined || fileMs <= beforeMs)) {
          results.push({
            path: fullPath,
            name: entry.name,
            isDir: false,
            size: stat.size,
            modified: formatDate(stat.mtimeMs / 1000),
            fileType: path.extname(entry.name).slice(1).toUpperCase() || 'FILE'
          });
        }
      }
    }
  }

  await walk(searchDir);
  return results;
}

// BUG-FIX: Made async to use fs.promises.readdir
async function searchContent(rootDir: string, query: string, recursive: boolean = true, filePattern?: string, caseSensitive: boolean = false, maxResults: number = 100): Promise<SearchResult[]> {
  const results: SearchResult[] = [];
  const searchDir = path.resolve(rootDir);

  const flags = caseSensitive ? '' : 'i';
  // BUG-15 FIX: Limit query length and escape special chars to prevent ReDoS
  const maxQueryLen = 100;
  if (query.length > maxQueryLen) {
    throw new Error(`Content search query too long (max ${maxQueryLen} chars)`);
  }
  const escapedQuery = query.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  let regex: RegExp;
  try {
    regex = new RegExp(escapedQuery, flags);
  } catch {
    regex = new RegExp(escapedQuery, flags);
  }

  async function walk(dir: string) {
    if (results.length >= maxResults) return;

    const entries = await fs.promises.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      if (results.length >= maxResults) return;

      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory() && recursive) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        if (filePattern && !fnmatchMatch(entry.name, filePattern, caseSensitive)) {
          continue;
        }

        try {
          const fileContent = await fs.promises.readFile(fullPath, 'utf8');
          if (regex.test(fileContent)) {
            const stat = await fs.promises.stat(fullPath);
            results.push({
              path: fullPath,
              name: entry.name,
              isDir: false,
              size: stat.size,
              modified: formatDate(stat.mtimeMs / 1000),
              fileType: path.extname(entry.name).slice(1).toUpperCase() || 'FILE'
            });
          }
        } catch {
          // Skip files that can't be read
        }
      }
    }
  }

  await walk(searchDir);
  return results;
}

function sortResults(results: SearchResult[], sortBy: string = 'name'): SearchResult[] {
  return [...results].sort((a, b) => {
    switch (sortBy) {
      case 'name':
        return a.name.toLowerCase().localeCompare(b.name.toLowerCase());
      case 'size':
        return (a.size || 0) - (b.size || 0);
      case 'date':
        return (a.modified || '').localeCompare(b.modified || '');
      case 'type':
        return (a.fileType || '').localeCompare(b.fileType || '');
      default:
        return 0;
    }
  });
}

function formatResults(results: SearchResult[], showDetails: boolean = true): string {
  if (results.length === 0) {
    return '\n' + '='.repeat(70) + '\n  No results found.\n' + '='.repeat(70);
  }

  let output = '\n' + '='.repeat(70) + '\n';
  output += `  Search Results\n  Total: ${results.length} item(s)\n`;
  output += '='.repeat(70) + '\n\n';

  results.forEach((r, i) => {
    const prefix = r.isDir ? '[DIR] ' : '[FILE] ';
    if (showDetails && !r.isDir) {
      const sizeStr = r.size !== undefined ? formatSize(r.size) : 'N/A';
      output += `  [${String(i + 1).padStart(4)}] ${prefix}${r.name.padEnd(35)} ${sizeStr.padStart(12)}  ${r.modified || 'N/A'}  (${r.fileType || '?'})\n`;
      output += `       Path: ${r.path}\n`;
    } else {
      output += `  [${String(i + 1).padStart(4)}] ${prefix}${r.path}\n`;
    }
  });

  output += '\n' + '='.repeat(70) + '\n';
  return output;
}
